# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            st1s.uk
tagline:          'Talk is Cheap. Show me the code...'
description:      'Notes and musings for my future self.'
url:              ""
baseurl:          https://st1s.uk/

site.author.name: st1s
site.author.email: st1s@st1s.uk

gems: [jekyll-paginate,jekyll-gist,redcarpet,pygments.rb]

paginate:         5

# Custom vars
version:          1.0.0
